using System.Threading.Tasks;
using System.Xml.Linq;

namespace TeXShift.Core.Logging
{
    /// <summary>
    /// Defines a contract for logging debug information during the conversion process.
    /// </summary>
    public interface IDebugLogger
    {
        /// <summary>
        /// Gets the full path to the directory where debug files are stored for the current session.
        /// </summary>
        string DebugSessionFolder { get; }

        /// <summary>
        /// Initializes a new debug session, preparing storage locations.
        /// </summary>
        void StartSession();

        /// <summary>
        /// Asynchronously logs the initial Markdown text extracted from OneNote.
        /// </summary>
        Task LogInputMarkdownAsync(string markdown);

        /// <summary>
        /// Asynchronously logs the original XML node that was processed.
        /// </summary>
        Task LogOriginalXmlAsync(XNode xmlNode);

        /// <summary>
        /// Asynchronously logs the OneNote XML generated by the converter.
        /// </summary>
        Task LogConvertedXmlAsync(XElement convertedXml);

        /// <summary>
        /// Asynchronously logs the final, complete XML of the OneNote page after the update.
        /// </summary>
        Task LogFinalPageXmlAsync(string finalXml);

        /// <summary>
        /// Asynchronously logs an exception that occurred during the process.
        /// </summary>
        Task LogErrorAsync(System.Exception ex);

        /// <summary>
        /// Asynchronously saves the raw XML of the current selection to a debug file.
        /// </summary>
        /// <returns>The full path to the saved file.</returns>
        Task<string> LogSelectionXmlAsync(XNode selectionXml);

        /// <summary>
        /// Asynchronously saves the raw XML of the entire page to a debug file.
        /// </summary>
        /// <returns>The full path to the saved file.</returns>
        Task<string> LogPageXmlAsync(string pageXml);
    }
}