using System.Linq;
using System.Text.RegularExpressions;

namespace TeXShift.Core.Math
{
    /// <summary>
    /// Adapts MathML generated by MathJax to OneNote's MathML renderer requirements.
    /// Handles attribute removal, whitespace compaction, bracket conversion,
    /// and other transformations required for OneNote compatibility.
    /// All methods are pure functions with no side effects.
    /// </summary>
    internal static class OneNoteMathMLAdapter
    {
        // Regex to match mspace elements with width attribute (OneNote doesn't support mspace width)
        private static readonly Regex MspaceRegex = new Regex(
            @"<mml:mstyle[^>]*>\s*<mml:mspace\s+width=""([^""]+)""\s*(?:/>|></mml:mspace>)\s*</mml:mstyle>|" +
            @"<mml:mspace\s+width=""([^""]+)""\s*(?:/>|></mml:mspace>)",
            RegexOptions.Compiled);

        /// <summary>
        /// Adapts MathML to OneNote format and wraps it for insertion.
        /// This is the main public API that orchestrates all transformations.
        /// </summary>
        /// <param name="mathml">The MathML string to adapt.</param>
        /// <returns>OneNote-compatible MathML wrapped in conditional comment with zero-width space sentinels.</returns>
        public static string AdaptToOneNote(string mathml)
        {
            if (string.IsNullOrWhiteSpace(mathml))
            {
                return string.Empty;
            }

            // Step 1: Remove MathJax-specific data attributes
            mathml = RemoveMathJaxAttributes(mathml);

            // Step 2: Compact whitespace
            mathml = CompactMathML(mathml);

            // Step 3: Convert mspace to Unicode space characters
            mathml = ConvertMspaceToUnicode(mathml);

            // Step 4: Convert matrix brackets to mfenced (for automatic stretching)
            // Must be done BEFORE AddFenceAttributeToBrackets
            mathml = ConvertMatrixBracketsToMfenced(mathml);

            // Step 5: Add fence="false" to brackets (verified fix for bracket/comma issues)
            mathml = AddFenceAttributeToBrackets(mathml);

            // Step 6: Split multi-character identifiers into single chars (stability fix)
            mathml = SplitMultiCharIdentifiers(mathml);

            // Step 7: Wrap in OneNote conditional comment with zero-width space sentinels
            const string zeroWidthSpan = "<span style='font-family:Arial'>\u200B</span>";
            return $"{zeroWidthSpan}<!--[if mathML]>{mathml}<![endif]-->{zeroWidthSpan}";
        }

        /// <summary>
        /// Removes MathJax-specific attributes that cause issues in OneNote.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with MathJax attributes removed.</returns>
        internal static string RemoveMathJaxAttributes(string mathml)
        {
            // Remove data-mjx-* attributes (MathJax internal, not standard MathML)
            var result = Regex.Replace(mathml, @"\s*data-mjx-[a-z]+=""[^""]*""", "", RegexOptions.IgnoreCase);

            // Remove stretchy="false" - without this, formulas like \int_{0}^{\pi} fail to render
            result = result.Replace(" stretchy=\"false\"", "");

            // Remove function application operator before parenthesis (verified fix for sin(x) etc.)
            result = Regex.Replace(result, @"<mml:mo>&#x2061;</mml:mo>\s*<mml:mo>\(", "<mml:mo>(");

            return result;
        }

        /// <summary>
        /// Compacts MathML by removing newlines and extra whitespace between tags.
        /// </summary>
        /// <param name="mathml">The MathML string to compact.</param>
        /// <returns>Compacted MathML with minimal whitespace.</returns>
        internal static string CompactMathML(string mathml)
        {
            // Remove newlines and multiple spaces
            var result = Regex.Replace(mathml, @"\s*\n\s*", "");
            result = Regex.Replace(result, @">\s+<", "><");
            return result.Trim();
        }

        /// <summary>
        /// Converts mspace width attributes to Unicode space characters.
        /// OneNote doesn't support mspace width, so we replace them with actual space characters.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with mspace elements replaced by Unicode spaces in mtext elements.</returns>
        internal static string ConvertMspaceToUnicode(string mathml)
        {
            return MspaceRegex.Replace(mathml, match =>
            {
                // Group 1 is for mstyle-wrapped mspace, Group 2 is for bare mspace
                var width = !string.IsNullOrEmpty(match.Groups[1].Value)
                    ? match.Groups[1].Value
                    : match.Groups[2].Value;

                var spaceChars = GetUnicodeSpaceForWidth(width);
                if (string.IsNullOrEmpty(spaceChars))
                {
                    return string.Empty; // Negative space or unknown width
                }
                return $"<mml:mtext>{spaceChars}</mml:mtext>";
            });
        }

        /// <summary>
        /// Converts brackets around tall content from mo elements to mfenced, which stretches automatically.
        /// Handles matrices, fractions, roots, etc.
        /// MathJax outputs: &lt;mrow&gt;&lt;mo&gt;(&lt;/mo&gt;&lt;mfrac&gt;...&lt;/mfrac&gt;&lt;mo&gt;)&lt;/mo&gt;&lt;/mrow&gt;
        /// OneNote needs: &lt;mfenced&gt;&lt;mrow&gt;&lt;mfrac&gt;...&lt;/mfrac&gt;&lt;/mrow&gt;&lt;/mfenced&gt;
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with tall-content brackets converted to mfenced elements.</returns>
        internal static string ConvertMatrixBracketsToMfenced(string mathml)
        {
            // Map opening brackets to their closing counterparts
            var bracketPairs = new[]
            {
                ("(", ")"),   // pmatrix, \left( \right)
                ("[", "]"),   // bmatrix, \left[ \right]
                ("{", "}"),   // Bmatrix, \left\{ \right\}
                ("|", "|"),   // vmatrix, \left| \right|
            };

            // Tall elements that should trigger bracket stretching
            // mtable (matrices), mfrac (fractions), msqrt/mroot (roots), munder/mover (limits)
            // mfenced included for nested brackets like \left( \left[ \frac{}{} \right] \right)
            var tallElements = "mtable|mfrac|msqrt|mroot|munder|mover|munderover|mfenced";

            foreach (var (open, close) in bracketPairs)
            {
                var escapedOpen = Regex.Escape(open);
                var escapedClose = Regex.Escape(close);

                // Pattern: <mrow><mo>BRACKET</mo>...CONTENT...<mo>BRACKET</mo></mrow>
                // The mrow wrapper is typical for \left...\right constructs
                var pattern = $@"<mml:mrow><mml:mo>{escapedOpen}</mml:mo>(.*?)<mml:mo>{escapedClose}</mml:mo></mml:mrow>";

                mathml = Regex.Replace(mathml, pattern, match =>
                {
                    var content = match.Groups[1].Value;
                    // Only convert to mfenced if content contains tall elements
                    if (Regex.IsMatch(content, $@"<mml:({tallElements})"))
                    {
                        var openAttr = open == "(" ? "" : $" open=\"{open}\"";
                        var closeAttr = close == ")" ? "" : $" close=\"{close}\"";
                        return $"<mml:mfenced{openAttr}{closeAttr}><mml:mrow>{content}</mml:mrow></mml:mfenced>";
                    }
                    // Keep original for non-tall content
                    return match.Value;
                }, RegexOptions.Singleline);
            }

            return mathml;
        }

        /// <summary>
        /// Adds fence="false" to bracket operators to prevent OneNote from converting them to mfenced.
        /// Without this, OneNote converts (a, b, c) to mfenced and deletes our commas.
        /// This must run AFTER ConvertMatrixBracketsToMfenced.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with fence="false" attributes added to bracket operators.</returns>
        internal static string AddFenceAttributeToBrackets(string mathml)
        {
            // Add fence="false" to parentheses
            var result = Regex.Replace(mathml, @"<mml:mo>\(</mml:mo>", "<mml:mo fence=\"false\">(</mml:mo>");
            result = Regex.Replace(result, @"<mml:mo>\)</mml:mo>", "<mml:mo fence=\"false\">)</mml:mo>");

            // Add fence="false" to square brackets
            result = Regex.Replace(result, @"<mml:mo>\[</mml:mo>", "<mml:mo fence=\"false\">[</mml:mo>");
            result = Regex.Replace(result, @"<mml:mo>\]</mml:mo>", "<mml:mo fence=\"false\">]</mml:mo>");

            // Add fence="false" to curly braces (if used as brackets, not grouping)
            result = Regex.Replace(result, @"<mml:mo>\{</mml:mo>", "<mml:mo fence=\"false\">{</mml:mo>");
            result = Regex.Replace(result, @"<mml:mo>\}</mml:mo>", "<mml:mo fence=\"false\">}</mml:mo>");

            return result;
        }

        /// <summary>
        /// Splits multi-character function names (like sin, cos, lim) into individual characters.
        /// OneNote re-parses MathML during page updates and splits them anyway,
        /// so we do it upfront to ensure formula stability across page edits.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with multi-character identifiers split into individual characters.</returns>
        internal static string SplitMultiCharIdentifiers(string mathml)
        {
            // Match <mml:mi>abc</mml:mi> or <mml:mo>abc</mml:mo> where content is 2+ letters
            var result = Regex.Replace(mathml, @"<mml:(mi|mo)>([a-zA-Z]{2,})</mml:\1>", match =>
            {
                var content = match.Groups[2].Value;
                var chars = string.Concat(content.Select(c => $"<mml:mi>{c}</mml:mi>"));
                return $"<mml:mrow>{chars}</mml:mrow>";
            });

            return result;
        }

        /// <summary>
        /// Returns Unicode space character(s) corresponding to the given em width.
        /// Maps em values to appropriate Unicode space characters that OneNote can render.
        /// </summary>
        /// <param name="width">The width value (e.g., "1em", "0.167em", "-0.167em").</param>
        /// <returns>Unicode space character(s), or null for negative/unknown widths.</returns>
        private static string GetUnicodeSpaceForWidth(string width)
        {
            if (string.IsNullOrEmpty(width)) return null;

            // Parse width value (e.g., "1em", "0.167em", "-0.167em")
            var match = Regex.Match(width, @"^(-?\d+(?:\.\d+)?)em$");
            if (!match.Success) return null;

            if (!double.TryParse(match.Groups[1].Value, out var emValue))
            {
                return null;
            }

            // Negative space - ignore (cannot simulate in OneNote)
            if (emValue < 0) return null;

            // Map em values to Unicode space characters
            // U+2003 = em space (1em)
            // U+2004 = three-per-em space (~0.333em)
            // U+2005 = four-per-em space (~0.25em)
            // U+2009 = thin space (~0.167em)
            // U+205F = medium mathematical space (~0.222em)

            if (emValue >= 1.5)
            {
                // 2em (qquad) = two em spaces
                return "\u2003\u2003";
            }
            if (emValue >= 0.8)
            {
                // 1em (quad) = one em space
                return "\u2003";
            }
            if (emValue >= 0.25)
            {
                // ~0.278em (thickspace \;) = three-per-em space
                return "\u2004";
            }
            if (emValue >= 0.2)
            {
                // ~0.222em (medspace \:) = medium mathematical space
                return "\u205F";
            }
            if (emValue >= 0.1)
            {
                // ~0.167em (thinspace \,) = thin space
                return "\u2009";
            }

            // Very small positive space - use thin space as minimum
            return "\u2009";
        }
    }
}
