using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using TeXShift.Core.Utils;

namespace TeXShift.Core.Math
{
    /// <summary>
    /// Adapts MathML generated by MathJax to OneNote's MathML renderer requirements.
    /// Handles attribute removal, whitespace compaction, bracket conversion,
    /// and other transformations required for OneNote compatibility.
    /// All methods are pure functions with no side effects.
    /// </summary>
    internal static class OneNoteMathMLAdapter
    {
        // Regex to match mspace elements with width attribute (OneNote doesn't support mspace width)
        private static readonly Regex MspaceRegex = new Regex(
            @"<mml:mstyle[^>]*>\s*<mml:mspace\s+width=""([^""]+)""\s*(?:/>|></mml:mspace>)\s*</mml:mstyle>|" +
            @"<mml:mspace\s+width=""([^""]+)""\s*(?:/>|></mml:mspace>)",
            RegexOptions.Compiled);

        // OneNote sometimes leaks attribute quote characters as visible text when MathML is embedded
        // via conditional comments. Using single quotes for attribute values avoids this behavior.
        private static readonly Regex DoubleQuotedAttributeRegex = new Regex(
            "=\"([^\"]*)\"",
            RegexOptions.Compiled);

        private static readonly Regex MtextRegex = new Regex(
            "<mml:mtext\\b[^>]*>(.*?)</mml:mtext>",
            RegexOptions.Compiled | RegexOptions.Singleline | RegexOptions.IgnoreCase);

        /// <summary>
        /// Adapts MathML to OneNote format and wraps it for insertion.
        /// This is the main public API that orchestrates all transformations.
        /// </summary>
        /// <param name="mathml">The MathML string to adapt.</param>
        /// <returns>OneNote-compatible MathML wrapped in a conditional comment and followed by a zero-width space sentinel.</returns>
        public static string AdaptToOneNote(string mathml)
        {
            if (string.IsNullOrWhiteSpace(mathml))
            {
                return string.Empty;
            }

            // Step 1: Remove MathJax-specific data attributes
            mathml = RemoveMathJaxAttributes(mathml);

            // Step 2: Remove semantics/annotation wrappers (OneNote strips them anyway)
            mathml = RemoveSemanticsAnnotations(mathml);

            // Step 3: Compact whitespace
            mathml = CompactMathML(mathml);

            // Step 4: Convert mspace to Unicode space characters
            mathml = ConvertMspaceToUnicode(mathml);

            // Step 5: Replace <mtext> with normal MathML tokens.
            // OneNote may insert visible stray quote characters when mtext is present in embedded MathML.
            mathml = ConvertMtextToNormalTokens(mathml);

            // Step 6: Convert matrix brackets to mfenced (for automatic stretching)
            // Must be done BEFORE AddFenceAttributeToBrackets
            mathml = ConvertMatrixBracketsToMfenced(mathml);

            // Step 7: Add fence="false" to brackets (verified fix for bracket/comma issues)
            mathml = AddFenceAttributeToBrackets(mathml);

            // Step 8: Split multi-character identifiers into single chars (stability fix)
            mathml = SplitMultiCharIdentifiers(mathml);

            // Step 9: Convert MathML attributes to single-quoted values to avoid OneNote inserting
            // visible stray quote characters around equations.
            mathml = ConvertAttributeQuotesToSingle(mathml);

            // Step 10: Wrap in a OneNote conditional comment with a trailing zero-width space sentinel.
            // Never add a leading sentinel: on import, OneNote makes the formula zone's first plain run
            // inherit the effective font of the immediately preceding run, so a fontless leading sentinel
            // renders a leading numeric token in the body font instead of the math font.
            // Avoid hardcoding fonts here; users can configure fonts in settings and OneNote will rewrite spans anyway.
            const string zeroWidthSpan = "<span lang='x-none'>\u200B</span>";
            return $"<!--[if mathML]>{mathml}<![endif]-->{zeroWidthSpan}";
        }

        private static string ConvertAttributeQuotesToSingle(string mathml)
        {
            if (string.IsNullOrWhiteSpace(mathml))
            {
                return string.Empty;
            }

            // Replace only attribute delimiters, not text nodes.
            return DoubleQuotedAttributeRegex.Replace(mathml, "='$1'");
        }

        /// <summary>
        /// Removes MathJax-specific attributes that cause issues in OneNote.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with MathJax attributes removed.</returns>
        internal static string RemoveMathJaxAttributes(string mathml)
        {
            // Remove data-mjx-* attributes (MathJax internal, not standard MathML)
            var result = Regex.Replace(mathml, @"\s*data-mjx-[a-z]+=""[^""]*""", "", RegexOptions.IgnoreCase);

            // Remove stretchy="false" - without this, formulas like \int_{0}^{\pi} fail to render
            result = result.Replace(" stretchy=\"false\"", "");

            // Remove function application operator before parenthesis (verified fix for sin(x) etc.)
            result = Regex.Replace(result, @"<mml:mo>&#x2061;</mml:mo>\s*<mml:mo>\(", "<mml:mo>(");

            return result;
        }

        /// <summary>
        /// Compacts MathML by removing newlines and extra whitespace between tags.
        /// </summary>
        /// <param name="mathml">The MathML string to compact.</param>
        /// <returns>Compacted MathML with minimal whitespace.</returns>
        internal static string CompactMathML(string mathml)
        {
            // Remove newlines and multiple spaces
            var result = Regex.Replace(mathml, @"\s*\n\s*", "");
            result = Regex.Replace(result, @">\s+<", "><");
            return result.Trim();
        }

        /// <summary>
        /// Removes MathML semantics wrappers and embedded annotations (e.g., TeX source).
        /// OneNote removes these during round-trips, so we strip them upfront for stability.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with semantics/annotation elements removed.</returns>
        internal static string RemoveSemanticsAnnotations(string mathml)
        {
            if (string.IsNullOrWhiteSpace(mathml))
            {
                return string.Empty;
            }

            // Remove annotation and annotation-xml blocks
            var result = Regex.Replace(mathml, @"<(?:mml:)?annotation(?:-xml)?[^>]*>.*?</(?:mml:)?annotation(?:-xml)?>",
                "", RegexOptions.Singleline | RegexOptions.IgnoreCase);

            // Unwrap semantics tags while keeping the inner MathML
            result = Regex.Replace(result, @"<(?:mml:)?semantics[^>]*>", "", RegexOptions.IgnoreCase);
            result = Regex.Replace(result, @"</(?:mml:)?semantics>", "", RegexOptions.IgnoreCase);

            return result;
        }

        /// <summary>
        /// Converts mspace width attributes to Unicode space characters.
        /// OneNote doesn't support mspace width, so we replace them with actual space characters.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with mspace elements replaced by Unicode spaces in mtext elements.</returns>
        internal static string ConvertMspaceToUnicode(string mathml)
        {
            return MspaceRegex.Replace(mathml, match =>
            {
                // Group 1 is for mstyle-wrapped mspace, Group 2 is for bare mspace
                var width = !string.IsNullOrEmpty(match.Groups[1].Value)
                    ? match.Groups[1].Value
                    : match.Groups[2].Value;

                var spaceChars = GetUnicodeSpaceForWidth(width);
                if (string.IsNullOrEmpty(spaceChars))
                {
                    return string.Empty; // Negative space or unknown width
                }

                // Avoid <mtext> because OneNote may introduce visible artifacts when mtext is present.
                return $"<mml:mo>{spaceChars}</mml:mo>";
            });
        }

        internal static string ConvertMtextToNormalTokens(string mathml)
        {
            if (string.IsNullOrWhiteSpace(mathml))
            {
                return string.Empty;
            }

            return MtextRegex.Replace(mathml, match =>
            {
                string inner = match.Groups[1].Value ?? string.Empty;
                string decoded = OneNoteHtmlEntityDecoder.Decode(inner) ?? string.Empty;

                // Convert the decoded text into MathML tokens that OneNote renders consistently.
                // We wrap the result in an mrow so we replace one element with one element.
                string tokens = ConvertTextToMathTokens(decoded);
                return $"<mml:mrow>{tokens}</mml:mrow>";
            });
        }

        private static string ConvertTextToMathTokens(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return string.Empty;
            }

            var sb = new StringBuilder(capacity: text.Length * 24);

            foreach (char ch in text)
            {
                if (char.IsWhiteSpace(ch) || ch == '\u00A0')
                {
                    // Preserve spacing, but keep it out of <mtext>.
                    sb.Append("<mml:mo>&#xA0;</mml:mo>");
                    continue;
                }

                string escaped = EscapeXmlChar(ch);

                if (char.IsLetter(ch))
                {
                    // Units and plain text should not be italicized.
                    sb.Append("<mml:mi mathvariant='normal'>");
                    sb.Append(escaped);
                    sb.Append("</mml:mi>");
                }
                else if (char.IsDigit(ch))
                {
                    sb.Append("<mml:mn>");
                    sb.Append(escaped);
                    sb.Append("</mml:mn>");
                }
                else
                {
                    sb.Append("<mml:mo>");
                    sb.Append(escaped);
                    sb.Append("</mml:mo>");
                }
            }

            return sb.ToString();
        }

        private static string EscapeXmlChar(char ch)
        {
            switch (ch)
            {
                case '&': return "&amp;";
                case '<': return "&lt;";
                case '>': return "&gt;";
                case '"': return "&quot;";
                case '\'': return "&apos;";
                default: return ch.ToString();
            }
        }

        /// <summary>
        /// Converts brackets around tall content from mo elements to mfenced, which stretches automatically.
        /// Handles matrices, fractions, roots, etc.
        /// MathJax outputs: &lt;mrow&gt;&lt;mo&gt;(&lt;/mo&gt;&lt;mfrac&gt;...&lt;/mfrac&gt;&lt;mo&gt;)&lt;/mo&gt;&lt;/mrow&gt;
        /// OneNote needs: &lt;mfenced&gt;&lt;mrow&gt;&lt;mfrac&gt;...&lt;/mfrac&gt;&lt;/mrow&gt;&lt;/mfenced&gt;
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with tall-content brackets converted to mfenced elements.</returns>
        internal static string ConvertMatrixBracketsToMfenced(string mathml)
        {
            // Map opening brackets to their closing counterparts
            var bracketPairs = new[]
            {
                ("(", ")"),   // pmatrix, \left( \right)
                ("[", "]"),   // bmatrix, \left[ \right]
                ("{", "}"),   // Bmatrix, \left\{ \right\}
                ("|", "|"),   // vmatrix, \left| \right|
            };

            // Tall elements that should trigger bracket stretching
            // mtable (matrices), mfrac (fractions), msqrt/mroot (roots), munder/mover (limits)
            // mfenced included for nested brackets like \left( \left[ \frac{}{} \right] \right)
            var tallElements = "mtable|mfrac|msqrt|mroot|munder|mover|munderover|mfenced";

            foreach (var (open, close) in bracketPairs)
            {
                var escapedOpen = Regex.Escape(open);
                var escapedClose = Regex.Escape(close);

                // Pattern: <mrow><mo>BRACKET</mo>...CONTENT...<mo>BRACKET</mo></mrow>
                // The mrow wrapper is typical for \left...\right constructs
                var pattern = $@"<mml:mrow><mml:mo>{escapedOpen}</mml:mo>(.*?)<mml:mo>{escapedClose}</mml:mo></mml:mrow>";

                mathml = Regex.Replace(mathml, pattern, match =>
                {
                    var content = match.Groups[1].Value;
                    // Only convert to mfenced if content contains tall elements
                    if (Regex.IsMatch(content, $@"<mml:({tallElements})"))
                    {
                        var openAttr = open == "(" ? "" : $" open=\"{open}\"";
                        var closeAttr = close == ")" ? "" : $" close=\"{close}\"";
                        return $"<mml:mfenced{openAttr}{closeAttr}><mml:mrow>{content}</mml:mrow></mml:mfenced>";
                    }
                    // Keep original for non-tall content
                    return match.Value;
                }, RegexOptions.Singleline);
            }

            // Handle one-sided brackets (e.g., \begin{cases} produces left brace with empty right)
            // Pattern: <mrow><mo ...>{</mo>...CONTENT...<mo stretchy='true'></mo></mrow>
            mathml = ConvertOneSidedBracketsToMfenced(mathml, tallElements);

            return mathml;
        }

        /// <summary>
        /// Converts one-sided brackets (e.g., cases environment) to mfenced.
        /// MathJax outputs: &lt;mrow&gt;&lt;mo&gt;{&lt;/mo&gt;...&lt;mo stretchy='true'&gt;&lt;/mo&gt;&lt;/mrow&gt;
        /// OneNote needs: &lt;mfenced open="{" close=""&gt;...&lt;/mfenced&gt;
        /// </summary>
        private static string ConvertOneSidedBracketsToMfenced(string mathml, string tallElements)
        {
            // One-sided left brackets: { [ ( with empty right boundary
            var leftBrackets = new[] { "{", "[", "(" };

            foreach (var bracket in leftBrackets)
            {
                var escapedBracket = Regex.Escape(bracket);
                // Match: <mrow><mo ...>BRACKET</mo>...CONTENT...<mo ... stretchy="true" ...></mo></mrow>
                // The empty <mo> with stretchy="true" indicates an invisible boundary
                // Note: attributes use double quotes at this stage (single quote conversion happens later)
                var pattern = $@"<mml:mrow><mml:mo[^>]*>{escapedBracket}</mml:mo>(.*?)<mml:mo[^>]*stretchy=""true""[^>]*></mml:mo></mml:mrow>";

                mathml = Regex.Replace(mathml, pattern, match =>
                {
                    var content = match.Groups[1].Value;
                    if (Regex.IsMatch(content, $@"<mml:({tallElements})"))
                    {
                        var openAttr = bracket == "(" ? "" : $" open=\"{bracket}\"";
                        return $"<mml:mfenced{openAttr} close=\"\"><mml:mrow>{content}</mml:mrow></mml:mfenced>";
                    }
                    return match.Value;
                }, RegexOptions.Singleline);
            }

            return mathml;
        }

        /// <summary>
        /// Adds fence="false" to bracket operators to prevent OneNote from converting them to mfenced.
        /// Without this, OneNote converts (a, b, c) to mfenced and deletes our commas.
        /// This must run AFTER ConvertMatrixBracketsToMfenced.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with fence="false" attributes added to bracket operators.</returns>
        internal static string AddFenceAttributeToBrackets(string mathml)
        {
            // Add fence="false" to parentheses
            var result = Regex.Replace(mathml, @"<mml:mo>\(</mml:mo>", "<mml:mo fence=\"false\">(</mml:mo>");
            result = Regex.Replace(result, @"<mml:mo>\)</mml:mo>", "<mml:mo fence=\"false\">)</mml:mo>");

            // Add fence="false" to square brackets
            result = Regex.Replace(result, @"<mml:mo>\[</mml:mo>", "<mml:mo fence=\"false\">[</mml:mo>");
            result = Regex.Replace(result, @"<mml:mo>\]</mml:mo>", "<mml:mo fence=\"false\">]</mml:mo>");

            // Add fence="false" to curly braces (if used as brackets, not grouping)
            result = Regex.Replace(result, @"<mml:mo>\{</mml:mo>", "<mml:mo fence=\"false\">{</mml:mo>");
            result = Regex.Replace(result, @"<mml:mo>\}</mml:mo>", "<mml:mo fence=\"false\">}</mml:mo>");

            return result;
        }

        /// <summary>
        /// Splits multi-character function names (like sin, cos, lim) into individual characters.
        /// OneNote re-parses MathML during page updates and splits them anyway,
        /// so we do it upfront to ensure formula stability across page edits.
        /// </summary>
        /// <param name="mathml">The MathML string to process.</param>
        /// <returns>MathML with multi-character identifiers split into individual characters.</returns>
        internal static string SplitMultiCharIdentifiers(string mathml)
        {
            // Match <mml:mi>abc</mml:mi> or <mml:mo>abc</mml:mo> where content is 2+ letters
            var result = Regex.Replace(mathml, @"<mml:(mi|mo)>([a-zA-Z]{2,})</mml:\1>", match =>
            {
                var content = match.Groups[2].Value;
                var chars = string.Concat(content.Select(c => $"<mml:mi>{c}</mml:mi>"));
                return $"<mml:mrow>{chars}</mml:mrow>";
            });

            return result;
        }

        /// <summary>
        /// Returns Unicode space character(s) corresponding to the given em width.
        /// Maps em values to appropriate Unicode space characters that OneNote can render.
        /// </summary>
        /// <param name="width">The width value (e.g., "1em", "0.167em", "-0.167em").</param>
        /// <returns>Unicode space character(s), or null for negative/unknown widths.</returns>
        private static string GetUnicodeSpaceForWidth(string width)
        {
            if (string.IsNullOrEmpty(width)) return null;

            // Parse width value (e.g., "1em", "0.167em", "-0.167em")
            var match = Regex.Match(width, @"^(-?\d+(?:\.\d+)?)em$");
            if (!match.Success) return null;

            if (!double.TryParse(match.Groups[1].Value, out var emValue))
            {
                return null;
            }

            // Negative space - ignore (cannot simulate in OneNote)
            if (emValue < 0) return null;

            // Map em values to Unicode space characters
            // U+2003 = em space (1em)
            // U+2004 = three-per-em space (~0.333em)
            // U+2005 = four-per-em space (~0.25em)
            // U+2009 = thin space (~0.167em)
            // U+205F = medium mathematical space (~0.222em)

            if (emValue >= 1.5)
            {
                // 2em (qquad) = two em spaces
                return "\u2003\u2003";
            }
            if (emValue >= 0.8)
            {
                // 1em (quad) = one em space
                return "\u2003";
            }
            if (emValue >= 0.25)
            {
                // ~0.278em (thickspace \;) = three-per-em space
                return "\u2004";
            }
            if (emValue >= 0.2)
            {
                // ~0.222em (medspace \:) = medium mathematical space
                return "\u205F";
            }
            if (emValue >= 0.1)
            {
                // ~0.167em (thinspace \,) = thin space
                return "\u2009";
            }

            // Very small positive space - use thin space as minimum
            return "\u2009";
        }
    }
}
