<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <RootNamespace>TeXShift.AddIn</RootNamespace>
    <AssemblyName>TeXShift.AddIn</AssemblyName>
    <EmbedOneNoteInteropTypes>true</EmbedOneNoteInteropTypes>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <PropertyGroup>
    <TeXShiftSigningKeyPath Condition="'$(TeXShiftSigningKeyPath)' == ''">$(MSBuildThisFileDirectory)..\..\texshift_key.snk</TeXShiftSigningKeyPath>
    <SignAssembly Condition="Exists('$(TeXShiftSigningKeyPath)')">true</SignAssembly>
    <AssemblyOriginatorKeyFile Condition="'$(SignAssembly)' == 'true'">$(TeXShiftSigningKeyPath)</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Interop.Microsoft.Office.Interop.OneNote" Version="1.1.0.2" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="MicrosoftOfficeCore" Version="15.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeXShift.Core\TeXShift.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Ribbon.xml" />
    <Resource Include="Resources\TeXShift.ico" />
    <None Remove="Lib\mathjax\**\*" />
    <None Remove="Lib\mermaid\**\*" />
    <Content Include="Lib\mathjax\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Lib\mermaid\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
